# Generated by Django 5.0.6 on 2024-06-20 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Skin_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Тип кожи')),
            ],
            options={
                'verbose_name': 'Тип кожи',
                'verbose_name_plural': 'Типы кожи',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='skin_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='soap.skin_type', verbose_name='Тип кожи'),
        ),
    ]
