# Generated by Django 5.0.6 on 2024-06-27 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('soap', '0003_effect_ingredients_product_effect_product_ingredient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dostavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_d', models.TextField(verbose_name='Вид доставки')),
                ('price', models.IntegerField(verbose_name='Стоимость доставки')),
            ],
            options={
                'verbose_name': 'Вид доставки',
                'verbose_name_plural': 'Виды доставки',
            },
        ),
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberZakaz', models.TextField(verbose_name='Номер заказа')),
                ('name', models.TextField(verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=15, verbose_name='телефон')),
                ('adress', models.TextField(verbose_name='Адрес доставки')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('dostavka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soap.dostavka')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Данные заказа',
                'verbose_name_plural': 'Данные заказов',
            },
        ),
        migrations.CreateModel(
            name='ZakazProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='количество')),
                ('adress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soap.zakaz')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soap.product')),
            ],
            options={
                'verbose_name': 'Заказанные продукты',
                'verbose_name_plural': 'Заказанные продукты',
            },
        ),
    ]
