# Generated by Django 5.0.6 on 2024-06-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soap', '0006_zakaz_koment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dostavka',
            name='time_d',
            field=models.TextField(null=True, verbose_name='Время доставки'),
        ),
    ]
